name: PluginManager
main: tk.rht0910.plugin_manager.Main
version: 0.4.5

commands:
   pman:
      description: Root command in PluginManager.
      usage: /<command> [args]
      permission: pluginmanager.help